name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Temporary Environment
        id: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.SECRET_TOKEN }}
          BRANCH: pr-preview-${{ github.event.pull_request.number }}
          FOLDER: build

      - name: Comment Preview URL on Pull Request
        if: success() && github.event.pull_request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            const branchName = `pr-preview-${{ github.event.pull_request.number }}`;
            const repoName = `${context.repo.owner}/${context.repo.repo}`;
            const { data: { html_url: issueUrl } } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview available at: https://${repoName}/${branchName}`
            });
            console.log(`Commented on ${issueUrl}`);
