name: Preview React App in Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Temporary Environment
        id: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.SECRET_TOKEN }}
          BRANCH: pr-preview-${{ github.event.pull_request.number }}
          FOLDER: build

      - name: Comment Preview URL
        if: steps.deploy.outcome == 'success'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            const { data: { html_url: issueUrl } } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview available at: https://finepo-nt.github.io/pr-preview-${{ github.event.pull_request.number }}`
            })
            console.log(`Commented on ${issueUrl}`)
