name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Preview Folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          publish_dir: ./build
          publish_branch: ${{ github.ref_slug }}
          publish_dir_prefix: github-preview

      - name: Comment Preview URL on Pull Request
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          script: |
            const { data: { html_url: issueUrl } } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview available at: https://finepo-nt.github.io/${{ github.ref_slug }}/github-preview`
            })
            console.log(`Commented on ${issueUrl}`)
